from crud_module import *
from class_albums import info


if __name__ == '__main__':

    save_many_query = "insert into tbl_albums(userid, title) \
                           values(%s, %s)"
    save_many_params = (
        (1,'quidem molestiae enim'),
        (1, 'sunt qui excepturi placeat culpa'),
        (1, 'omnis laborum odio'),
        (1, 'non esse culpa molestiae omnis sed optio'),
        (1, 'eaque aut omnis a'),
        (1, 'natus impedit quibusdam illo est'),
        (1, 'quibusdam autem aliquid et et quia'),
        (1, 'qui fuga est a eum'),
        (1, 'saepe unde necessitatibus rem'),
        (1, 'distinctio laborum qui'),
        (2, 'quam nostrum impedit mollitia quod et dolor'),
        (2, 'consequatur autem doloribus natus consectetur'),
        (2, 'ab rerum non rerum consequatur ut ea unde'),
        (2, 'ducimus molestias eos animi atque nihil'),
        (2, 'ut pariatur rerum ipsum natus repellendus praesentium'),
        (2, 'voluptatem aut maxime inventore autem magnam atque repellat'),
        (2, 'aut minima voluptatem ut velit'),
        (2, 'nesciunt quia et doloremque'),
        (2, 'velit pariatur quaerat similique libero omnis quia'),
        (2, 'voluptas rerum iure ut enim'),
        (3, 'repudiandae voluptatem optio est consequatur rem in temporibus et'),
        (3, 'et rem non provident vel ut'),
        (3, 'incidunt quisquam hic adipisci sequi'),
        (3, 'dolores ut et facere placeat'),
        (3, 'vero maxime id possimus sunt neque et consequatur'),
        (3, 'quibusdam saepe ipsa vel harum'),
        (3, 'id non nostrum expedita'),
        (3, 'omnis neque exercitationem sed dolor atque maxime aut cum'),
        (3, 'inventore ut quasi magnam itaque est fugit'),
        (3, 'tempora assumenda et similique odit distinctio error'),
        (4, 'adipisci laborum fuga laboriosam'),
        (4, 'reiciendis dolores a ut qui debitis non quo labore'),
        (4, 'iste eos nostrum'),
        (4, 'cumque voluptatibus rerum architecto blanditiis'),
        (4, 'et impedit nisi quae magni necessitatibus sed aut pariatur'),
        (4, 'nihil cupiditate voluptate neque'),
        (4, 'est placeat dicta ut nisi rerum iste'),
        (4, 'unde a sequi id'),
        (4, 'ratione porro illum labore eum aperiam sed'),
        (4, 'voluptas neque et sint aut quo odit'),
        (5, 'ea voluptates maiores eos accusantium officiis tempore mollitia consequatur'),
        (5, 'tenetur explicabo ea'),
        (5, 'aperiam doloremque nihi'),
        (5, 'sapiente cum numquam officia consequatur vel natus quos suscipit'),
        (5, 'tenetur quos ea unde est enim corrupti qui'),
        (5, 'molestiae voluptate non'),
        (5, 'temporibus molestiae aut'),
        (5, 'modi consequatur culpa aut quam soluta alias perspiciatis laudantium'),
        (5, 'ut aut vero repudiandae voluptas ullam voluptas at consequatur'),
        (5, 'sed qui sed quas sit ducimus dolor'),
        (6, 'odit laboriosam sint quia cupiditate animi quis'),
        (6, 'necessitatibus quas et sunt at voluptatem'),
        (6, 'est vel sequi voluptatem nemo quam molestiae modi enim'),
        (6, 'aut non illo amet perferendis'),
        (6, 'qui culpa itaque omnis in nesciunt architecto error'),
        (6, 'omnis qui maiores tempora officiis omnis rerum sed repellat'),
        (6, 'libero excepturi voluptatem est architecto quae voluptatum officia tempora'),
        (6, 'nulla illo consequatur aspernatur veritatis aut error delectus et'),
        (6, 'eligendi similique provident nihil'),
        (6, 'omnis mollitia sunt aliquid eum consequatur fugit minus laudantium'),
        (7, 'delectus iusto et'),
        (7, 'eos ea non recusandae iste ut quasi'),
        (7, 'velit est quam'),
        (7, 'autem voluptatem amet iure quae'),
        (7, 'voluptates delectus iure iste qui'),
        (7, 'velit sed quia dolor dolores delectus'),
        (7, 'ad voluptas nostrum et nihil'),
        (7, 'qui quasi nihil aut voluptatum sit dolore minima'),
        (7, 'qui aut est'),
        (7, 'et deleniti unde'),
        (8, 'et vel corporis'),
        (8, 'unde exercitationem ut'),
        (8, 'quos omnis officia'),
        (8, 'quia est eius vitae dolor'),
        (8, 'aut quia expedita non'),
        (8, 'dolorem magnam facere itaque ut reprehenderit tenetur corrupti'),
        (8, 'cupiditate sapiente maiores iusto ducimus cum excepturi veritatis quia'),
        (8, 'est minima eius possimus ea ratione velit et'),
        (8, 'ipsa quae voluptas natus ut suscipit soluta quia quidem'),
        (8, 'id nihil reprehenderit'),
        (9, 'quibusdam sapiente et'),
        (9, 'recusandae consequatur vel amet unde'),
        (9, 'aperiam odio fugiat'),
        (9, 'est et at eos expedita'),
        (9, 'qui voluptatem consequatur aut ab quis temporibus praesentium'),
        (9, 'eligendi mollitia alias aspernatur vel ut iusto'),
        (9, 'aut aut architecto'),
        (9, 'quas perspiciatis optio'),
        (9, 'sit optio id voluptatem est eum et'),
        (9, 'est vel dignissimos'),
        (10, 'repellendus praesentium debitis officiis'),
        (10, 'incidunt et et eligendi assumenda soluta quia recusandae'),
        (10, 'nisi qui dolores perspiciatis'),
        (10, 'quisquam a dolores et earum vitae'),
        (10, 'consectetur vel rerum qui aperiam modi eos aspernatur ipsa'),
        (10, 'unde et ut molestiae est molestias voluptatem sint'),
        (10, 'est quod aut'),
        (10, 'omnis quia possimus nesciunt deleniti assumenda sed autem'),
        (10, 'consectetur ut id impedit dolores sit ad ex aut'),
        (10, 'enim repellat iste')
        )
    save_many(save_many_query, save_many_params)


